import OpenAI from 'openai'
import { Client } from '@modelcontextprotocol/client'
import { StdioClientTransport, getDefaultEnvironment } from '@modelcontextprotocol/client/stdio'
import { fileURLToPath } from 'node:url'

import { getAlexProductBrief } from './alex.js'

const openai = process.env.OPENAI_API_KEY
  ? new OpenAI({ apiKey: process.env.OPENAI_API_KEY })
  : null

function getText(value) {
  if (value === null || value === undefined) return ''
  if (typeof value === 'string') return value.trim()
  return String(value).trim()
}

async function loadLiveSnapshot(question) {
  const mcpServerPath = fileURLToPath(
    new URL('../mcp/serve.js', import.meta.url),
  )
  const backendRoot = fileURLToPath(new URL('..', import.meta.url))

  const transport = new StdioClientTransport({
    command: process.execPath,
    args: [mcpServerPath],
    cwd: backendRoot,
    env: {
      ...getDefaultEnvironment(),
      GOOGLE_SHEET_ID: process.env.GOOGLE_SHEET_ID || '',
      NODE_ENV: process.env.NODE_ENV || 'development',
    },
  })

  const client = new Client({ name: 'tastemate-alex-mcp', version: '1.0.0' })

  await client.connect(transport)

  try {
    const toolResult = await client.callTool({
      name: 'live_dashboard_snapshot',
      arguments: { question },
    })

    if (toolResult.isError) {
      const errText = Array.isArray(toolResult.content)
        ? toolResult.content.map((c) => getText(c?.text || c)).join(' ')
        : 'MCP tool error'

      throw new Error(errText)
    }

    const snapshot = toolResult.structuredContent || (() => {
      const firstText = Array.isArray(toolResult.content)
        ? getText(toolResult.content[0]?.text)
        : ''

      if (!firstText) return {}

      try {
        return JSON.parse(firstText)
      } catch {
        return { raw: firstText }
      }
    })()

    return { snapshot, toolName: 'live_dashboard_snapshot' }
  } finally {
    await transport.close()
  }
}

export async function getAlexMcpProductBrief(linaBrief) {
  if (!linaBrief) {
    throw new Error('Alex (MCP) requires a Lina brief as input.')
  }

  const question = linaBrief.summary || linaBrief.designGoals?.join(' ') || 'Create an AI product brief for TasteMate.'

  const { snapshot } = await loadLiveSnapshot(question)

  // System prompt: ask LLM to return JSON matching the Alex schema.
  const systemPrompt = `You are Alex, an AI product maker. Return a JSON object matching the following keys: productGoals (array), customerRequirements (array), productOpportunities (array), coreFeatures (array of {feature,description}), aiWorkflow (array of {stage,description}), customerJourneyMapping (array), designToProductTranslation (array), implementationConsiderations (array), recommendationsForSam (array). Keep answers concise.`

  if (openai) {
    try {
      const completion = await openai.chat.completions.create({
        model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
        temperature: 0.35,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'system', content: `MCP snapshot:\n${JSON.stringify(snapshot, null, 2)}` },
          { role: 'user', content: `Lina brief:\n${JSON.stringify(linaBrief, null, 2)}` },
          { role: 'user', content: 'Respond with valid JSON only.' },
        ],
      })

      const text = completion.choices?.[0]?.message?.content?.trim()

      if (text) {
        try {
          const parsed = JSON.parse(text)

          return {
            agent: 'Alex',
            role: 'AI Product Maker (LLM)',
            generatedAt: new Date().toISOString(),
            handoffFrom: 'Lina',
            source: { agent: 'Lina', dataSource: 'Lina Experience Brief + MCP snapshot' },
            ...parsed,
            mcpSnapshot: snapshot,
          }
        } catch (err) {
          console.warn('Failed to parse LLM output as JSON, falling back.', err)
        }
      }
    } catch (err) {
      console.error('OpenAI call failed for Alex MCP agent:', err)
    }
  }

  // Fallback: deterministic local generator
  const fallback = getAlexProductBrief(linaBrief)

  return { ...fallback, note: 'Generated by local fallback (OpenAI unavailable or produced invalid JSON).', mcpSnapshot: snapshot }
}

export const alexMcpMetadata = {
  name: 'Alex (MCP LLM)',
  role: 'AI Product Maker',
  description: 'Alex powered by an LLM and grounded via MCP snapshot.',
}
